version: '3.5'

services:
  proxylb:
    image: 'nginx:mylatest'
    container_name: proxylb
    ports:
      - '80:80'
    volumes:
      - './configs/proxylb.conf:/etc/nginx/conf.d/default.conf'
    networks:
      network:
        aliases:
          - proxylb
    restart: always

  nginx01:
    image: 'nginx:mylatest'
    container_name: nginx01
    ports:
      - '8000:80'
    volumes:
      - '/opt/myapp01:/usr/share/nginx/html/myapp01'
      - './configs/myapp01.conf:/etc/nginx/conf.d/default.conf'
    networks:
      network:
        aliases:
          - nginx01
    links:
      - proxylb

  nginx02:
    image: 'nginx:mylatest'
    container_name: nginx02
    ports:
      - '8001:80'
    volumes:
      - '/opt/myapp01:/usr/share/nginx/html/myapp01'
      - './configs/myapp01.conf:/etc/nginx/conf.d/default.conf'
    networks:
      network:
        aliases:
          - nginx02
    links:
      - proxylb

  nginx03:
    image: 'nginx:mylatest'
    container_name: nginx03
    ports:
      - '8002:80'
    volumes:
      - '/opt/myapp01:/usr/share/nginx/html/myapp01'
      - './configs/myapp01.conf:/etc/nginx/conf.d/default.conf'
    networks:
      network:
        aliases:
          - nginx03
    links:
      - proxylb

  nginx04:
    image: 'nginx:mylatest'
    container_name: nginx04
    ports:
      - '8080:80'
    volumes:
      - '/opt/myapp02:/usr/share/nginx/html/myapp02'
      - './configs/myapp02.conf:/etc/nginx/conf.d/default.conf'
    networks:
      network:
        aliases:
          - nginx04
    links:
      - proxylb

  nginx05:
    image: 'nginx:mylatest'
    container_name: nginx05
    ports:
      - '8081:80'
    volumes:
      - '/opt/myapp02:/usr/share/nginx/html/myapp02'
      - './configs/myapp02.conf:/etc/nginx/conf.d/default.conf'
    networks:
      network:
        aliases:
          - nginx05
    links:
      - proxylb

  nginx06:
    image: 'nginx:mylatest'
    container_name: nginx06
    ports:
      - '8082:80'
    volumes:
      - '/opt/myapp02:/usr/share/nginx/html/myapp02'
      - './configs/myapp02.conf:/etc/nginx/conf.d/default.conf'
    networks:
      network:
        aliases:
          - nginx06
    links:
      - proxylb

networks:
  network:
    driver: bridge
